default: &default
  adapter: postgresql
  encoding: unicode
  username: thiago
  password: 123
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: api_auth_ready_development

test:
  <<: *default
  database: api_auth_ready_test

production:
  <<: *default
  database: api_auth_ready_production
  username: api_auth_ready
  password: <%= ENV['API_AUTH_READY_DATABASE_PASSWORD'] %>
